# Generated by Django 4.2.4 on 2024-07-17 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(max_length=2)),
                ('idPeriodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='tasks.periodoacademico')),
            ],
        ),
    ]
