# Generated by Django 5.0.7 on 2024-07-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodoacademico',
            name='fechaFin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='fechaInicio',
            field=models.DateField(),
        ),
    ]
