# Generated by Django 5.0.7 on 2024-07-22 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_periodoacademico_fechafin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaPeriodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numMatriculados', models.PositiveIntegerField(max_length=3)),
                ('numAprobados', models.PositiveIntegerField(max_length=3)),
                ('numReprobados', models.PositiveIntegerField(max_length=3)),
                ('numDesertores', models.PositiveIntegerField(max_length=3)),
                ('numForaneos', models.PositiveIntegerField(max_length=3)),
                ('idAdministrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to=settings.AUTH_USER_MODEL)),
                ('idCiclo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.ciclo')),
                ('idPeriodo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.periodoacademico')),
            ],
        ),
    ]
